
services:
  api:
    build: .
    container_name: vehicle_allocation_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: vehicle_allocation_db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: